import { Alex_Brush, Montserrat } from "next/font/google";
import Trc from "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";

const alexBrush = Alex_Brush({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-alexBrush",
});

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log(Trc);
  return (
    <html lang="en">
      <body
        className={`${alexBrush.variable} ${montserrat.variable} overflow-x-hidden relative`}
      >
        <Header />
        {Trc}
        {children}
        <Footer />
      </body>
    </html>
  );
}
